### ISSUE TITLE
Generic Function Removes Return Type T

### ISSUE THREAD

**Issue by pequots34** [cqfn/diKTat#1000]
## Describe the bug

Not enough information to infer type variable T

Before 
      public suspend inline fun <reified T> get(block: HttpRequestBuilder.() -> Unit): T {
        return httpClient.request(
            base().apply(
                block
            )
        )
    }

After

  public suspend inline fun <reified T> get(block: HttpRequestBuilder.() -> Unit) = httpClient.request(
        base().apply(
            block
        )
    )

## Expected behavior

  public suspend inline fun <reified T> get(block: HttpRequestBuilder.() -> Unit) :T = httpClient.request(
        base().apply(
            block
        )
    )

## Observed behavior

  public suspend inline fun <reified T> get(block: HttpRequestBuilder.() -> Unit) = httpClient.request(
        base().apply(
            block
        )
    )

## Environment information
* diktat version: 1.0.0-rc.2
* build tool (maven/gradle): gradle
* how is diktat run (CLI, plugin, etc.): plugin
* kotlin version: 1.5.21
* operating system: mac
* link to a project (if your project is public): N/A

**Comment by akuleshov7** [comment]
@pequots34 Hi and many thanks for this bug report!

could you please add more information about the generic type?
I see that the following code is compiled succesfully, so Kotlin can infer the gerneric type.

```
class A<T>(val a: T) {
    public fun foo(): T {
        return a
    }
    public suspend inline fun bar() =
         foo()
}
```

Where the type `T` comes from in your example? Could you please modify my example to make it more reproducible?

**Comment by akuleshov7** [comment]
If it is a real issue we would need to update https://github.com/cqfn/diKTat/blob/master/info/guide/diktat-coding-convention.md#r3.6.2 point 6

**Comment by Cheshiriks** [comment]
Hi @pequots34. Am I correct in understanding that this breaks your code?
This is our code style. When the function contains only a single expression, it can be written as expression function. 
https://github.com/cqfn/diKTat/blob/master/info/guide/diktat-coding-convention.md#r3.6.2 point 6

**Comment by pequots34** [comment]
yes, the code won't compile as it can't infer the type correctly.

**Comment by petertrr** [comment]
Hey @pequots34 , could you please provide code example one more time or edit in your original comment? Your original example doesn't have `reified` and it's not clear, where type parameter is originally declared (is it parameter of enclosing class? or of the function?).

**Comment by pequots34** [comment]
yes, will do

**Comment by pequots34** [comment]
@petertrr updated

**Comment by akuleshov7** [comment]
> @petertrr updated

We cannot see the example. Could you please copy it to a separate comment in this thread?

**Comment by akuleshov7** [comment]
This is the small reproducer:

```
class A<T>(val a: T) {
    public fun <E> foo(): E? {
        return null
    }
    public suspend inline fun bar(): T? =
        foo()
}
```

**Comment by pequots34** [comment]
Not enough information to infer type variable T

Before
public suspend inline fun get(block: HttpRequestBuilder.() -> Unit): T {
return httpClient.request(
base().apply(
block
)
)
}

After

public suspend inline fun get(block: HttpRequestBuilder.() -> Unit) = httpClient.request(
base().apply(
block
)
)

Expected behavior

public suspend inline fun get(block: HttpRequestBuilder.() -> Unit) :T = httpClient.request(
base().apply(
block
)
)

Observed behavior

public suspend inline fun get(block: HttpRequestBuilder.() -> Unit) = httpClient.request(
base().apply(
block
)
)

Steps to Reproduce

Environment information

diktat version: 1.0.0-rc.2
build tool (maven/gradle): gradle
how is diktat run (CLI, plugin, etc.): plugin
kotlin version: 1.5.21
operating system: mac
link to a project (if your project is public): N/A
