### ISSUE TITLE
expect/actual removing abstract modifier 

### ISSUE THREAD

**Issue by pequots34** [cqfn/diKTat#1001]
## Describe the bug

expect/actual removing abstract modifier 

## Expected behavior

actual abstract class CoroutineTest actual constructor() {

    /**
     * Test rule
     */
    @get:Rule
    var coroutineTestRule = CoroutineTestRule()

    /**
     * Run test
     *
     * @param T
     * @param block
     * @receiver a Coroutine Scope
     */
    actual fun <T> runTest(block: suspend CoroutineScope.() -> T) {
        runBlocking {
            block()
        }
    }
}

## Observed behavior

@RunWith(AndroidJUnit4::class)
actual class CoroutineTest actual constructor() {
    /**
     * Test rule
     */
    @get:Rule
    var coroutineTestRule = CoroutineTestRule()

    /**
     * Run test
     *
     * @param T
     * @param block
     * @receiver a Coroutine Scope
     */
    actual fun <T> runTest(block: suspend CoroutineScope.() -> T) {
        runBlocking {
            block()
        }
    }
}

## Environment information
* diktat version: 1.0.0-rc.2
* build tool (maven/gradle): gradle
* how is diktat run (CLI, plugin, etc.): plugin
* kotlin version: 1.5.21
* operating system: mac
* link to a project (if your project is public): N/A

**Comment by akuleshov7** [comment]
Hi, thank you for your report. Reproduced it here: [Diktat DEMO](https://ktlint-demo.herokuapp.com/)
![image](https://user-images.githubusercontent.com/58667063/127126122-246978cc-7957-46be-988b-9976d713e9ad.png)


We will take a fix for this issue in **1.0.0 version.**
Actually we don't even have rules in our [CodeStyle](https://github.com/cqfn/diKTat/blob/master/info/guide/diktat-coding-convention.md) for actual/expect modifiers... Need to add them!

**Comment by pequots34** [comment]
Thank you!

**Comment by Cheshiriks** [comment]
Hi @pequots34, Yes, that's how it should work. If the class does not contain abstract methods, then the modifier is not required.
We will correct the logic, we will change abstract to open modifier if the class was expected to inherit.

**Comment by pequots34** [comment]
@Cheshiriks will this make it into 1.0 release?

**Comment by akuleshov7** [comment]
> @Cheshiriks will this make it into 1.0 release?
will be in RC3 (will be released next week) and in 1.0.0 release

**Comment by pequots34** [comment]
tried on rc3 and its still not working as expected. it removes abstract from actual and causes the project to fail to compile.

Actual constructor of 'CoroutineTest' has no corresponding expected declaration

/**
 * Coroutine test
 *
 * @constructor Create empty Coroutine test
 */
actual class CoroutineTest actual constructor() {
    /**
     * Run test
     *
     * @param T
     * @param block
     * @receiver a Coroutine Scope
     * @return JS dynamic
     * @throws Throwable
     */
    @OptIn(DelicateCoroutinesApi::class)
    actual fun <T> runTest(block: suspend CoroutineScope.() -> T): dynamic {
        return GlobalScope.launch(Dispatchers.Main) {
            async(block = block).asPromise()
        }
    }
}
