### ISSUE TITLE
NEWLINES_RULES: fix can cause long lines

### ISSUE THREAD

**Issue by orchestr7** [cqfn/diKTat#1339]
Need to think of how we can prevent the creation of long lines by this rule .

![image](https://user-images.githubusercontent.com/58667063/171236147-6fd474ef-6508-4b09-b323-34b74d47125e.png)

**Comment by Arrgentum** [comment]
Error in WhiteSpaceRule. 
in OPERATOR_REFERENCE logic -> KtBinaryExpression
