### ISSUE TITLE
All tests should be tagged with special tag

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#163]
Junit5 supports tag @Tag: https://junit.org/junit5/docs/current/user-guide/#writing-tests-tagging-and-filtering
We should Tag tests with the name of the Rule (Warning aka MY_WARNING from Warnings.kt ) that it is testing

**Comment by akuleshov7** [comment]
Please note, that Junit annotations do not support non-compile time constants. That's why we need code generation for these constants. PLease see how **codegen** can be done in Kotlin

**Comment by petertrr** [comment]
Codegen can be done using [kotlinpoet](https://square.github.io/kotlinpoet/) and [maven exec plugin](https://www.mojohaus.org/exec-maven-plugin/java-mojo.html). It should be done during `generate sources` maven phase, generated sources should go into `target` directory.
