### ISSUE TITLE
Exceptions when running dikTat with -F flag

### ISSUE THREAD

**Issue by aktsay6** [cqfn/diKTat#203]
java -jar ktlint -F diktat.jar C:\Users\rat91\IdeaProjects\diKTat\diktat-rules\src\main\kotlin\org\cqfn\diktat\ruleset\constants

This command was used when exception appeared

![image](https://user-images.githubusercontent.com/48321920/91569470-7b164780-e94e-11ea-9dff-26fa8a21de6b.png)

**Comment by petertrr** [comment]
Command should be 'java -jar ktlint -R diktat.jar -F ...`

**Comment by aktsay6** [comment]
yes, params were wrong
