### ISSUE TITLE
Describe rules for calls chain inside parenthesis

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#241]
In line like `if (node.treeParent.findChildByType(MODIFIER_LIST)?.findChildByType(OVERRIDE_KEYWORD) != null)` is it better to simply follow functional style
```kotlin
if (node
    .treeParent
    .findChildByType(MODIFIER_LIST)
    ?.findChildByType(OVERRIDE_KEYWORD) != null)
```
or suggest to extract complex expression into separate variable?

**Comment by petertrr** [comment]
@akuleshov7 , as discussed, this should be added as a new rule in chapter 3

**Comment by akuleshov7** [comment]
@akuleshov7 will need to add this to our codestyle. 
We need to prohibit complex calculations in the if-conditions
