### ISSUE TITLE
What will be printed? Is it bug in Kotlin?

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#327]
```
fun main() {
    var a = 1
    class A {
        var a = 2

        fun foo() = a
    }

    println(A().foo())
}
```

1 will be printed

**Comment by akuleshov7** [comment]
https://github.com/JetBrains/kotlin/blob/master/spec-docs/NameResolution.adoc

**Comment by petertrr** [comment]
So I think this is the case here: https://kotlinlang.org/docs/reference/this-expressions.html#implicit-this
However, I still don't understand exact conditions for `this` resolving here

**Comment by petertrr** [comment]
https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS4zLjcyIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiZnVuIG1haW4oKSB7XG4gICAgY2xhc3MgQSB7XG4gICAgICAgIHZhciBhID0gMlxuXG4gICAgICAgIGZ1biBmb28oKSA9IGFcbiAgICB9XG5cbiAgICB2YXIgYSA9IDFcbiAgICBwcmludGxuKEEoKS5mb28oKSlcbn0ifQ==

https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS4zLjcyIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiZnVuIG1haW4oKSB7XG4gICAgdmFyIGEgPSAxXG4gICAgY2xhc3MgQSB7XG4gICAgICAgIHZhciBhID0gMlxuXG4gICAgICAgIGZ1biBmb28oKSA9IHRoaXMuYVxuICAgIH1cblxuICAgIHByaW50bG4oQSgpLmZvbygpKVxufSJ9

**Comment by akuleshov7** [comment]
https://stackoverflow.com/questions/65492914/variables-shadowing-in-kotlin-for-inner-classes-how-variables-are-resolved
