### ISSUE TITLE
Trailing comma: new feature from Kotlin 1.4

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#419]
Kotlin 1.4 introduce the trailing comma feature. So we need to support it now not only for ENUMs as we did it before, but our code-style should force people to do this. For example:
```
fun foo(
    a: Int,
    b: String, // <--- this trailing comma is extremely useful for merging conflicts and swapping easily line without changing them
) 

val colors = listOf(
    "red",
    "green",
    "blue", //trailing comma
)
```

same should be done for function calls/constructor arguments/e.t.c

Kotlin supports trailing commas in the following cases:

Enumerations
Value arguments
Class properties and parameters
Function value parameters
Parameters with optional type (including setters)
Indexing suffix
Lambda parameters
when entry
Collection literals (in annotations)
Type arguments
Type parameters
Destructuring declarations

**Comment by petertrr** [comment]
It should be pretty easy to implement from the rules side, but the most important question here is: how should user specify language version? We should either support this setting in our plugin(s) or yml config, or once again consider moving from ktlint to detekt as backend, because detekt already supports such settings.

**Comment by akuleshov7** [comment]
please have a look at #728 first

**Comment by petertrr** [comment]
@kentr0w implement it like this: if there is a newline after the last element in parameter/argument list, then there should be a comma after it.
Obviousely, check that kotlin version is >= 1.4

**Comment by petertrr** [comment]
@kentr0w please add it like this in the code style:
```
Since kotlin 1.4 you can use trailing comma in most list structures, including value argument lists, type parameter lists, parameters in indexing etc. Usage of trailing comma is recommended for long lists since it makes merging and resolving merge conflicts really seamless. If you use trailing comma, you should also put a line break after it.

Invalid code:
fun foo(
    a: Int,
    b: Int) {}

Valid code:
fun foo(
    a: Int,
    b: Int,
) {}
```
