### ISSUE TITLE
Long supertype list on the new line

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#420]
For classes with a long supertype list, put a line break after the colon and align all supertype names horizontally:

```kotlin​
class MyFavouriteVeryLongClassHolder :
    MyLongHolder<MyFavouriteVeryLongClass>(),
    SomeOtherInterface,
    AndAnotherOne {
​
}
```

**Comment by petertrr** [comment]
No, I suppose, it's not implemented. I'll add it to `NewlinesRule`. I also couldn't find a rule for argument list separation, when there are more than two arguments, even though I though we have it already.

**Comment by akuleshov7** [comment]
Need to add it to the codestyle then
