### ISSUE TITLE
Must have, extremely needed: split the code style to make it readable and useful 

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#432]
What we need:
1) Code style should be split by rules (separate files) and by chapters (separate directories)
2) Code style should be linked with the diktat documentation
3) We should create autogenerator for a code style document (to unify it)

**Comment by petertrr** [comment]
Do you mean simply splitting code style into many parts or moving these parts closer to code (as rules' KDocs) and then extracting from there?

**Comment by petertrr** [comment]
Implemented in different PRs, including: #466 #494 #496 #558 #582  #645
