### ISSUE TITLE
Assertion failed: anchorBefore == null || anchorBefore.getTreeParent() == parent

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#436]
## Describe the bug
Code `class A {val x = 0 }` (when there is text right after `{`) causes and error, relevant part of stacktrace:
```
at org.cqfn.diktat.ruleset.rules.BlockStructureBraces.checkOpenBraceEndLine(BlockStructureBraces.kt:185)
	at org.cqfn.diktat.ruleset.rules.BlockStructureBraces.checkOpenBraceOnSameLine(BlockStructureBraces.kt:176)
	at org.cqfn.diktat.ruleset.rules.BlockStructureBraces.checkClass(BlockStructureBraces.kt:84)
	at org.cqfn.diktat.ruleset.rules.BlockStructureBraces.visit(BlockStructureBraces.kt:66)
```

## Environment information
* diktat version: 0.1.2

**Comment by akuleshov7** [comment]
wow! just wanted to report
```
class HttpClient(var name: String) {
    var url: String = ""
    var port: String = ""
    var timeout = 0

    fun doRequest() {}
}

fun main() {
    val httpClient = HttpClient("myConnection")
            .apply {
                url = "http://pushkin.com"
                port = "8080"
                timeout = 100
            }
            .doRequest()
}
```

reproduced on the following. 
@petertrr @kentr0w who did this rule?

**Comment by akuleshov7** [comment]
when you will be checking that - please check that we really put here a newline when formatting long functional statements (as descrbed in Rule 3.6 line break style rules if the line is split):

```
  val value = otherValue!!
          .map { x -> x }
          .filter {
              val a = true
              true
          } // <----- newline here
          .size
```

**Comment by petertrr** [comment]
> wow! just wanted to report

In this example the error might be because of `{}` - rule expects that there is some other node after an opening brace. 

@kentr0w , as an original implementer of `BlockStructureBraces` rule could you investigate this bug?

**Comment by petertrr** [comment]
> when you will be checking that - please check that we really put here a newline when formatting long functional statements (as descrbed in Rule 3.6 line break style rules if the line is split):

Yes, we do it in `NewlinesRule`, you can take a look at `FunctionalStyleExpected` in `NewlinesRuleFixTest` as an example.

**Comment by akuleshov7** [comment]
```
/*
 * Copyright (c) Your Company Name Here. 2010-2020
 */

class HttpClient(var name: String) {
    var url: String = ""
    var port: String = ""
    var timeout = 0

    fun doRequest() {}
}

fun main() {
    val httpClient = HttpClient("myConnection")
        .apply {
            url = "http://pushkin.com"
            port = "8080"
            timeout = 100
        }
        .doRequest()
}
```

**Comment by petertrr** [comment]
Actually, the very simple example
```kotlin
/*
 * aaa
 */
 
class A
```
throws this exception. ktlint 0.37.1, diktat 0.1.2

**Comment by petertrr** [comment]
A lot of errors we got are due to missing `package` directive.
@kentr0w please add package directives to the examples above when trying to debug them
