### ISSUE TITLE
Recommendation 6.1.8: avoid using custom getters and setters

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#444]
Kotlin has a perfect mechanism of [properties](https://kotlinlang.org/docs/reference/properties.html#properties-and-fields).
Kotlin compiler automatically generates `get` and `set` methods for properties and also lets the possibility to override it:
```kotlin 
// Bad example ======
class A {
    var size: Int = 0
        set(value) {
            println("Side effect")
            field = value
        }
        get() = this.hashCode() * 2
}
```

From the callee code these methods look like an access to this property: `A().isEmpty = true` for setter and `A().isEmpty` for getter.
But in all cases it is very confusing when `get` and `set` are overriden for a developer who uses this particular class. 
Developer expects to get the value of the property, but receives some unknown value and some extra side effect hidden by the custom getter/setter. 
Use extra functions for it instead.

Good example:
```kotlin 
// Bad example ======
class A {
    var size: Int = 0
    fun initSize(value: Int) {
        // some custom logic
    }
    
    fun goodNameThatDescribesThisGetter() = this.hashCode() * 2
}
```

**Comment by petertrr** [comment]
Also worth adding that if custom logic is executed only once, then custom getter can be converted to lazy initialization

**Comment by petertrr** [comment]
Code style guide needs to be edited, there is incorrect comment in the good example

**Comment by akuleshov7** [comment]
> Code style guide needs to be edited, there is incorrect comment in the good example

which one?

**Comment by akuleshov7** [comment]
> Also worth adding that if custom logic is executed only once, then custom getter can be converted to lazy initialization
We will not be able to detect it, I guess. But yes, codestyle can be enhanced. What do you think?

**Comment by petertrr** [comment]
> > Code style guide needs to be edited, there is incorrect comment in the good example
> 
> which one?

There is part of text that says 'Good example: ` // Bad example `'

**Comment by petertrr** [comment]
> > Also worth adding that if custom logic is executed only once, then custom getter can be converted to lazy initialization
>  We will not be able to detect it, I guess. But yes, codestyle can be enhanced. What do you think?

Yes, we are not able to detect it, but it can be added to code style and, maybe, to warning message
