### ISSUE TITLE
Diktat 0.1.3 in multiplatform projects can't be used using current instructions

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#476]
When trying to use diktat 0.1.3 in [diktat-demo](https://github.com/akuleshov7/diktat-demo), I'm facing some issues, because we now use kotlinx.serialization which supports multiplatform, therefore somehow jvm artifact variants should be specified for diktat check.

One of possible options that I found is to add
```kotlin
val ktlint: Configuration by configurations.creating {
    attributes.attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage::class, Usage.JAVA_RUNTIME))
}
```
but this still doesn't solve the problem and leads to the next exception (`KotlinNothingValueException`)

**Comment by akuleshov7** [comment]
Is it due to multiplatform and kotlinJs in demo?
How it would work on the previous version with normal JS?

**Comment by petertrr** [comment]
I forgot to mention, I'm talking about diktat check, not regular application run.
Because for diktat check we create a separate gradle configuration with it's own dependency set.
Yes, I believe it's because of multiplatform.

**Comment by petertrr** [comment]
Nevermind, I've found the issue: the plugin `io.spring.dependency-management` was overriding some dependency versions and putting kotlin 1.3.72 there. Removing this plugin and setting spring boot dependencies versions manually solves issues with both diktat check and application run,
