### ISSUE TITLE
GENERIC_VARIABLE_WRONG_DECLARATION should allow some exceptions

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#498]
This rules makes a lot of sense for, e.g., collection factory methods (`val list = listOf<Type>()`), but there are methods designed so that semantically it makes sense to place generic type in method call, like `val properties = node.collectDescendantsOfType<KtProperty>` IMO looks more clear than `val properties: List<KtProperty> = collectDescendantsOfType()`.

Another example:
```kotlin
val e = assertThrows<IllegalArgumentException> {
            DiktatRuleSetProvider(file.absolutePath).get()
        }
```

**Comment by kentr0w** [comment]
The rule works correctly according to the documentation. And there are examples to show that it's better not to change:
```kotlin
val a = ArrayList<String>()
val b: List<String> = a
```
you must write `List<String>` to correctly cast. Therefore, it is beneficial for us to move to the right (because it works in 99% of cases)
