### ISSUE TITLE
There should not be null-checks

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#510]
Kotlin has special operators for null-checks like `let`, `also` and `?:`.
Need to use these contructions instead of explicit comparison with null like: `if (a ==null) {}`

**Comment by petertrr** [comment]
I think we should narrow down exact cases for this, like
* only `if` with single branch (`if (x != null)`) can be replaced with `?.let` or other function
* only ternary-like if expressions (`x = if (y != null) y else z`) can be replaced with `?:`
etc.
