### ISSUE TITLE
Newline should be inserted before `?:` in functional call chain

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#554]
## Describe the bug
```kotlin
fun foo() {
    foo.bar().baz().qux() ?: baz
}
```
should be fixed to
```kotlin
fun foo() {
    foo
        .bar()
        .baz()
        .qux()
        ?: baz
}
```
but `?:` isn't placed on a separate line

## Environment information
* diktat version: 0.1.5

**Comment by akuleshov7** [comment]
what to do with simple expressions?
I guess for simple expressions need to have it on the same line.
```
a ?: b
```
=>

is fine in both ways:
```a ?: b```
and 
```
a 
    ?: b
```

because in some cases linelength rule can fix it

**Comment by petertrr** [comment]
I think rules should be the same as for usual calls chain: 
* if right-hand side of `?:` is a simple expression and left-hand side too, then they can be on the same line, but also can be split if the line is too long
* if RHS expression requires line breaks, `?:` should start on a new line
* if LHS already has line breaks, `?:` should start on a new line
