### ISSUE TITLE
Properties in an object are sorted the way that uninitialzied properties are accessed

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#573]
## Describe the bug
PakcageNaming-> companion object is invalid after diktat fix

## Environment information
* diktat version: 0.1.5
* git HEAD: 0bc75c82

**Comment by kentr0w** [comment]
This [PR](https://github.com/cqfn/diKTat/commit/2a29553d9aa994b8aebf5d4c4b2d146f6de5ea54) solved this bug
