### ISSUE TITLE
Introduce DiktatRule to wrap c.p.k.c.Rule

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#606]
<file name="C:\Users\a00543375\Desktop\diKTat\diktat-rules\src\test\kotlin\org\cqfn\diktat\util\DiktatRuleSetProvider4Test.kt">
		<error line="1" column="1" severity="error" message="Internal Error (diktat-ruleset:kdoc-comments). Please create a ticket at https://github.com/pinterest/ktlint/issues (if possible, provide the source code that triggered an error) (cannot be auto-corrected)" source="" />
	</file>

Such errors should be properly handled

**Comment by petertrr** [comment]
This is when exception is not handled on our side and is thrown up to ktlint. We could probably wrap ktlint's rules to catch all exceptions, or do you have something else in mind?

**Comment by petertrr** [comment]
@Cheshiriks forget everything I just told you, we are doing it differently.

**Comment by petertrr** [comment]
1. Create a wrapper around ktlint's `Rule`:
    ```kotlin
        abstreact class DiktatRule(val warnings: Set<Warnings>, id: String) : Rule(id) {
            override fun visit() {
                if (check()) return
                else logic()
             }

           abstract fun check(): Boolean // whether this rule should be executed, checks if all warnings from `warnings` are disabled
           abstract fun logic(node: ...)  // previously `visit`
        }
    ```
2. Inside `DiktatRule::visit` wrap everything in `try-catch` and output custom message if unhandled error is encountered
3. Probably, terminate application instead of simply logging Internal Error

**Comment by petertrr** [comment]
If we perform this refactoring (checking whether rule should be executed before `visit` method), we might gain a performance boost. It would be interesting to measure it (at least at first see whether CI checks have become faster). If so, we can create a map of rules to boolean status - whether they are enabled, according to both `enabled` and `disabledChapters`.
