### ISSUE TITLE
Inspect the logic of the data class rule

### ISSUE THREAD

**Issue by aktsay6** [cqfn/diKTat#750]
## Describe the bug
```kotlin
class Credentials(auth: String) {
    val first = ...
    val second = ...

    init {
        ...
        foo(auth)
    }

...
}
```

The question is should it be considered as data class?

## Environment information
* diktat version: 0.4.0

**Comment by petertrr** [comment]
The important thing here is that `auth` is used inside `init` block to set class properties, and the logic is too complicated to refactor using a secondary constructor which delegates to primary.
