### ISSUE TITLE
Diktat should not be printing the same error again when the Kotlin version is not specified

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#751]
> Task :diktatFix
[ERROR] 2021-02-07 23:51:16 Kotlin version not specified in the configuration file. Will be using 1.4.21 version
[ERROR] 2021-02-07 23:51:16 Kotlin version not specified in the configuration file. Will be using 1.4.21 version
[ERROR] 2021-02-07 23:51:16 Kotlin version not specified in the configuration file. Will be using 1.4.21 version
[ERROR] 2021-02-07 23:51:16 Kotlin version not specified in the configuration file. Will be using 1.4.21 version
[ERROR] 2021-02-07 23:51:16 Kotlin version not specified in the configuration file. Will be using 1.4.21 version
[ERROR] 2021-02-07 23:51:16 Kotlin version not specified in the configuration file. Will be using 1.4.21 version
[ERROR] 2021-02-07 23:51:16 Kotlin version not specified in the configuration file. Will be using 1.4.21 version
[ERROR] 2021-02-07 23:51:16 Kotlin version not specified in the configuration file. Will be using 1.4.21 version
[ERROR] 2021-02-07 23:51:16 Kotlin version not specified in the configuration file. Will be using 1.4.21 version

**Comment by petertrr** [comment]
Hmm, that's strange, we specifically made `kotlinVersion` in configuration a lazy property so that the message will be printed once. @kentr0w , need to investigate.
