### ISSUE TITLE
Rule for collapsing IF-statements

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#801]
https://jsparrow.github.io/rules/collapse-if-statements.html#code-changes

See this rule! We definitely should have this in a diktat

**Comment by akuleshov7** [comment]
It should have the config - how much nested ifs it can detect. For example - if 3, then diktat will trigger only on the following statements: 
```
if() {
   if() {
       if() {
```

**Comment by akuleshov7** [comment]
Need to be accurate, you should not be suggesting to unify several ifs, if it will make the line longer than maximum line_linegth symbols

**Comment by petertrr** [comment]
> Need to be accurate, you should not be suggesting to unify several ifs, if it will make the line longer than maximum line_length symbols

We already have a rule for line length, though, and we usually let it fix everything. Unless we come up with some specific logic here, I suggest not to bother with line length in this rule
