### ISSUE TITLE
Rule for collapsing and enhancing Boolean conditions

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#809]
Many developers are incorrectly using a Boolean logic in their programs and their conditions are becoming more and more complex. We need to detect such boolean conditions that **can** be simplified and automatically fix them. 

There are different Java libraries for it, like: https://github.com/bpodgursky/jbool_expressions
But need to understand if we really need to simplify these conditions or not, so this is the plan:
1) Find rules of the simplification that can be applied
2) Support checkers that will raise a warning if a condition can be simplified (becomes shorter)
3) Check libraries for the simplification and choose the best (or create your own libraries)
4) Support autofixers

**Comment by aktsay6** [comment]
In future we can consider simplifying boolean methods as well. Example: `a.and(b)`
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-boolean/
