### ISSUE TITLE
There should be an option to disable MAGIC_NUMBER rule in test sources 

### ISSUE THREAD

**Issue by petertrr** [cqfn/diKTat#832]

**Comment by ntoskrnl** [comment]
Maybe even different set of rules for test files / directory?

**Comment by petertrr** [comment]
Hi @ntoskrnl! Some of our rules already behave differently depending on whether file is from main or test source set. E.g, we don't enforce KDocs on public classes from test sources. We detect main sources by `srcDirectories` parameter from common config serction, and test source sets by `testDirs` parameter. Do you mean something similar?
