### ISSUE TITLE
diktat incorrectly calculates package name (domain name duplication)

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#85]
```
[INFO]    [ktlint] C:\Users\pwx5333130\Documents\diKTat\diktat-common\src\test\kotlin\org\cqfn\diktat\test\JsonReaderTest.kt:1:9: [5] package name does not match the directory hierarchy for this file, the path to the file is: org.cqfn.diktat.test.org.cqfn.diktat.test
```

**Comment by petertrr** [comment]
Also `[INFO]    [ktlint] C:\Users\pwx5333130\Documents\diKTat\diktat-rules\src\test\kotlin\org\cqfn\diktat\ruleset\chapter1\EnumValueCaseTest.kt:1:9: [5] package name does not match the directory hierarchy for this file, the path to the file is: org.cqfn.diktat.test.org.cqfn.diktat.ruleset.chapter1`
