### ISSUE TITLE
 [INLINE_CLASS_CAN_BE_USED] inline class can be used

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#904]
This rule is triggered on the interfaces. I do not think that it should work in that way, isn't it?

**Comment by akuleshov7** [comment]
Also need to support them as value classes: https://kotlinlang.org/docs/inline-classes.html#members

**Comment by petertrr** [comment]
We will need to have version-dependent logic for this; and for 1.5 we should respect the following requirements before suggesting value class: https://github.com/Kotlin/KEEP/blob/master/proposals/inline-classes.md#current-limitations

**Comment by petertrr** [comment]
Let's split this issue into two: the short-term bugfix would be limiting `inline` for language versions < 1.5 and filtering out interfaces, and the second one will be proper support of value classes
